apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loki-clusterrolebinding
  uid: 44cf0938-b4b3-499a-8a78-6681eb33b4d3
  resourceVersion: '1302'
  creationTimestamp: '2025-01-27T16:34:02Z'
  labels:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: 3.3.2
    helm.sh/chart: loki-6.25.0
  annotations:
    meta.helm.sh/release-name: loki
    meta.helm.sh/release-namespace: loki
  selfLink: >-
    /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/loki-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: loki
    namespace: loki
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loki-clusterrole
